begin_unit
comment|'#!/usr/bin/env python'
nl|'\n'
nl|'\n'
comment|'# Copyright (c) 2009 Twisted Matrix Laboratories.'
nl|'\n'
comment|'# See LICENSE for details.'
nl|'\n'
nl|'\n'
name|'from'
name|'twisted'
op|'.'
name|'internet'
name|'import'
name|'defer'
newline|'\n'
name|'from'
name|'twisted'
op|'.'
name|'python'
name|'import'
name|'failure'
op|','
name|'util'
newline|'\n'
nl|'\n'
string|'"""\nThis example shows an important concept that many deferred newbies\n(myself included) have trouble understanding. \n\nwhen an error occurs in a callback, the first errback after the error\noccurs will be the next method called. (in the next example we\'ll\nsee what happens in the \'chain\' after an errback).\n"""'
newline|'\n'
nl|'\n'
DECL|class|Counter
name|'class'
name|'Counter'
op|'('
name|'object'
op|')'
op|':'
newline|'\n'
DECL|variable|num
indent|'    '
name|'num'
op|'='
number|'0'
newline|'\n'
nl|'\n'
DECL|function|handleFailure
dedent|''
name|'def'
name|'handleFailure'
op|'('
name|'f'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'print'
string|'"errback"'
newline|'\n'
name|'print'
string|'"we got an exception: %s"'
op|'%'
op|'('
name|'f'
op|'.'
name|'getTraceback'
op|'('
op|')'
op|','
op|')'
newline|'\n'
name|'f'
op|'.'
name|'trap'
op|'('
name|'RuntimeError'
op|')'
newline|'\n'
nl|'\n'
DECL|function|handleResult
dedent|''
name|'def'
name|'handleResult'
op|'('
name|'result'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'Counter'
op|'.'
name|'num'
op|'+='
number|'1'
newline|'\n'
name|'print'
string|'"callback %s"'
op|'%'
op|'('
name|'Counter'
op|'.'
name|'num'
op|','
op|')'
newline|'\n'
name|'print'
string|'"\\tgot result: %s"'
op|'%'
op|'('
name|'result'
op|','
op|')'
newline|'\n'
name|'return'
string|'"yay! handleResult was successful!"'
newline|'\n'
nl|'\n'
DECL|function|failAtHandlingResult
dedent|''
name|'def'
name|'failAtHandlingResult'
op|'('
name|'result'
op|')'
op|':'
newline|'\n'
indent|'    '
name|'Counter'
op|'.'
name|'num'
op|'+='
number|'1'
newline|'\n'
name|'print'
string|'"callback %s"'
op|'%'
op|'('
name|'Counter'
op|'.'
name|'num'
op|','
op|')'
newline|'\n'
name|'print'
string|'"\\tgot result: %s"'
op|'%'
op|'('
name|'result'
op|','
op|')'
newline|'\n'
name|'print'
string|'"\\tabout to raise exception"'
newline|'\n'
name|'raise'
name|'RuntimeError'
op|','
string|'"whoops! we encountered an error"'
newline|'\n'
nl|'\n'
nl|'\n'
nl|'\n'
DECL|function|behindTheScenes
dedent|''
name|'def'
name|'behindTheScenes'
op|'('
name|'result'
op|')'
op|':'
newline|'\n'
comment|'# equivalent to d.callback(result)'
nl|'\n'
nl|'\n'
comment|"# now, let's make the error happen in the first callback"
nl|'\n'
nl|'\n'
indent|'    '
name|'if'
name|'not'
name|'isinstance'
op|'('
name|'result'
op|','
name|'failure'
op|'.'
name|'Failure'
op|')'
op|':'
comment|'# ---- callback'
newline|'\n'
indent|'        '
name|'try'
op|':'
newline|'\n'
indent|'            '
name|'result'
op|'='
name|'failAtHandlingResult'
op|'('
name|'result'
op|')'
newline|'\n'
dedent|''
name|'except'
op|':'
newline|'\n'
indent|'            '
name|'result'
op|'='
name|'failure'
op|'.'
name|'Failure'
op|'('
op|')'
newline|'\n'
dedent|''
dedent|''
name|'else'
op|':'
comment|'# ---- errback'
newline|'\n'
indent|'        '
name|'pass'
newline|'\n'
nl|'\n'
nl|'\n'
comment|'# note: this callback will be skipped because'
nl|'\n'
comment|'# result is a failure'
nl|'\n'
nl|'\n'
dedent|''
name|'if'
name|'not'
name|'isinstance'
op|'('
name|'result'
op|','
name|'failure'
op|'.'
name|'Failure'
op|')'
op|':'
comment|'# ---- callback '
newline|'\n'
indent|'        '
name|'try'
op|':'
newline|'\n'
indent|'            '
name|'result'
op|'='
name|'handleResult'
op|'('
name|'result'
op|')'
newline|'\n'
dedent|''
name|'except'
op|':'
newline|'\n'
indent|'            '
name|'result'
op|'='
name|'failure'
op|'.'
name|'Failure'
op|'('
op|')'
newline|'\n'
dedent|''
dedent|''
name|'else'
op|':'
comment|'# ---- errback'
newline|'\n'
indent|'        '
name|'pass'
newline|'\n'
nl|'\n'
nl|'\n'
dedent|''
name|'if'
name|'not'
name|'isinstance'
op|'('
name|'result'
op|','
name|'failure'
op|'.'
name|'Failure'
op|')'
op|':'
comment|'# ---- callback'
newline|'\n'
indent|'        '
name|'pass'
newline|'\n'
dedent|''
name|'else'
op|':'
comment|'# ---- errback'
newline|'\n'
indent|'        '
name|'try'
op|':'
newline|'\n'
indent|'            '
name|'result'
op|'='
name|'handleFailure'
op|'('
name|'result'
op|')'
newline|'\n'
dedent|''
name|'except'
op|':'
newline|'\n'
indent|'            '
name|'result'
op|'='
name|'failure'
op|'.'
name|'Failure'
op|'('
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
nl|'\n'
DECL|function|deferredExample
dedent|''
dedent|''
dedent|''
name|'def'
name|'deferredExample'
op|'('
op|')'
op|':'
newline|'\n'
indent|'    '
name|'d'
op|'='
name|'defer'
op|'.'
name|'Deferred'
op|'('
op|')'
newline|'\n'
name|'d'
op|'.'
name|'addCallback'
op|'('
name|'failAtHandlingResult'
op|')'
newline|'\n'
name|'d'
op|'.'
name|'addCallback'
op|'('
name|'handleResult'
op|')'
newline|'\n'
name|'d'
op|'.'
name|'addErrback'
op|'('
name|'handleFailure'
op|')'
newline|'\n'
nl|'\n'
name|'d'
op|'.'
name|'callback'
op|'('
string|'"success"'
op|')'
newline|'\n'
nl|'\n'
nl|'\n'
dedent|''
name|'if'
name|'__name__'
op|'=='
string|"'__main__'"
op|':'
newline|'\n'
indent|'    '
name|'behindTheScenes'
op|'('
string|'"success"'
op|')'
newline|'\n'
name|'print'
string|'"\\n-------------------------------------------------\\n"'
newline|'\n'
name|'Counter'
op|'.'
name|'num'
op|'='
number|'0'
newline|'\n'
name|'deferredExample'
op|'('
op|')'
newline|'\n'
nl|'\n'
dedent|''
endmarker|''
end_unit
